name: Confie em Deus.
favicon: null
layout_spectrum: 0.5158740805927664
typography_spectrum: 0.7549104574136436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3962904359214008
  lightness: 0.5447659881319851
  saturation: 0.4008544906973839
  rhythmicContrast: 0.854498777538538
purpose: []
